partitions: 3
replication: 1

topics:
  - name: 
  

retry_topics:
  - name: 
    retention_ms: 50
  - name: 
    retention_ms: 300
  - name: 
    retention_ms: 1200

dlq_topics:
  - name: 